# Generated by Django 5.1.1 on 2026-05-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='usuario',
        ),
    ]
